In [2]:
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [4]:
x = np.arange(5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [14]:
# 역순으로 정렬
x[::-1]

array([4, 3, 2, 1, 0])

In [13]:
# 오름차순 정렬 (0~9 범위 내의 5개 숫자)
a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [8 6 9 7 3]
    


In [18]:
# 1. np.sort(자료) -> 원본 자체가 바뀌진 않음
print(np.sort(a))
print(a)

[3 6 7 8 9]
[8 6 9 7 3]


In [20]:
# 2. 자료.sort() -> 원본 자료에 반영
a.sort()
print(a)
b= np.random.randint(0, 10, 5)
np_print(b)

[3 6 7 8 9]

    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [5 2 2 7 3]
    


In [21]:
# np.argsort(자료)는 자료 내부의 아이템들을 순서대로 정렬하기 위해서
# 현재 인덱스 몇 번에 있는 자료를 어떤 순서로 배치해야 하는지 보여줌
np.argsort(b) # 정렬 전 자료의 인덱스 번호를 정렬 된 상태로 가져옴

array([1, 2, 4, 0, 3], dtype=int64)

In [22]:
# 0 이상 1 미만의 범위에서 무작위로 실수 값을 가지는 3행 3열의 배열 2개 생성
a = np.random.random((3,3))
b = np.random.random((3,3))
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.77093354 0.06516307 0.80366914]
 [0.30695734 0.30885578 0.09369577]
 [0.75284491 0.363851   0.92408136]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.217102   0.73589623 0.36006363]
 [0.33357321 0.19970156 0.0401308 ]
 [0.69582694 0.3063456  0.83797814]]
    


##### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (행 기준 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [23]:
# 기본 방향(axis=-1)
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.77093354 0.06516307 0.80366914]
 [0.30695734 0.30885578 0.09369577]
 [0.75284491 0.363851   0.92408136]]
    


array([[0.06516307, 0.77093354, 0.80366914],
       [0.09369577, 0.30695734, 0.30885578],
       [0.363851  , 0.75284491, 0.92408136]])

##### axis = 0 (열 기준 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [31]:
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.77093354 0.06516307 0.80366914]
 [0.30695734 0.30885578 0.09369577]
 [0.75284491 0.363851   0.92408136]]
    


array([[0.30695734, 0.06516307, 0.09369577],
       [0.75284491, 0.30885578, 0.80366914],
       [0.77093354, 0.363851  , 0.92408136]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [32]:
# 0부터 34까지 1씩 증가하는 값을 아이템으로 가지는 1차원 배열 생성
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [33]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소 접근
arr1[1]

1

In [35]:
# 1차원 배열 인덱싱을 통한 값 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [53]:
# 배열 arr1을 이용해 4x6 형태의 2차원 배열 생성
arr2 = arr1
np_print(arr2.reshape(4,6))
arr2 = arr2.reshape(4,6)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [54]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 열에 접근 : 1열
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [55]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
# 반환값 : 1d array
arr2[:, 0]

array([ 0,  6, 12, 18])

In [56]:
# 하나의 값에 접근
# 3행 3열
arr2[2, 2]

14

In [57]:
# 여러개의 행(row) 조회
arr2[[3, 0]]

array([[ 18,  19,  20,  21,  22, 100],
       [  0,   1,   2,   3,   4,   5]])

In [59]:
# 여러 개의 열(column) 조회(0번째, 2번째)
arr2[:, [0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [62]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])