In [3]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 변환

#### 1. 전치(Transpose) 
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음
    
<img src='img/transpose.png' width='200' height='200' align='left'>

In [29]:
# 1이상 12이하의 값을 가지는 3 x 4 구조의 배열 생성
arr1 = np.arange(1, 13).reshape(3, 4)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (3, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
    


In [30]:
# 전치행렬 생성
arr1_t = arr1.T
arr1_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 2. 배열 형태 변경
- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [31]:
# 다차원 배열을 1차원 배열로 변환
arr2 = arr1.ravel()

In [32]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (12,)  
    dimension : 1  
    dtype : int32
    data :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
    


In [34]:
# 변환 후 값 수정, 원본과 비교
arr2[0] = 10

In [35]:
arr1

array([[10,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# arr1을 6 * 2 형태로 바꾸되, 하나의 축에 대해서 -1로 처리해보세요.
arr3 = arr1.reshape(-1, 2)
arr3

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [37]:
# 변환 후 값 수정, 원본과 비교
arr3[0] = [100, 200]

In [38]:
arr1

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

#### 3. 요소 변경, 추가, 삭제

1) 요소 변경
- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우 
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [39]:
# 1이상 10미만의 범위 랜덤 정수값으로 3 x 5 구조를 가진 배열 생성
arr = np.random.randint(1, 10, (3, 5))
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 5)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3 3 4]
 [8 6 8 9 4]
 [2 5 2 5 9]]
    


In [40]:
arr2 = np.random.randint(1, 10, (3, 5))
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (3, 5)  
    dimension : 2  
    dtype : int32
    data :
 [[9 7 9 2 3]
 [3 9 4 1 5]
 [3 7 5 3 4]]
    


In [41]:
# 변경되는 배열의 요소 수가 동일한 경우 : reshape()와 동일한 결과물
# arr.reshape(3, 5)
arr.resize((5, 3))

In [42]:
arr.size

15

In [43]:
arr

array([[1, 2, 3],
       [3, 4, 8],
       [6, 8, 9],
       [4, 2, 5],
       [2, 5, 9]])

In [44]:
# 변경 후 배열의 요소 개수가 더 많은 경우

In [45]:
arr3 = np.resize(arr2, (6, 3))
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (6, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[9 7 9]
 [2 3 3]
 [9 4 1]
 [5 3 7]
 [5 3 4]
 [9 7 9]]
    


In [46]:
# refcheck=False인 경우 크기가 다를 때 0으로 남은 자리를 채워줌
arr.resize((6, 3), refcheck=False)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (6, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [3 4 8]
 [6 8 9]
 [4 2 5]
 [2 5 9]
 [0 0 0]]
    


In [47]:
# 변경되는 요소의 갯수가 더 적은 경우 : 마지막 남은 요소 삭제
# 크기가 원본과 resize를 이용했을때 다르다면 refcheck = False를 반드시 넣는다.
arr.resize((3, 3), refcheck=False)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [3 4 8]
 [6 8 9]]
    


2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [48]:
# 1 이상 10미만의 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 a 생성
# 10이상 19미만의 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 b 생성
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
    


In [49]:
# 2개의 배열 결합
# axis 지정X = (axis = None)
# arr1, arr2를 전부 1차원으로 바꾸고 그 다음에 길이 연장
np.append(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [50]:
# 2개의 배열 결합
# axis=0 : 행(row)단위 결합 / 열(column) 개수는 3개로 동일
np.append(a, b, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [51]:
# 2개의 배열 결합
# axis = 1 : 열(column)단위 결합 / 행(row) 개수는 3개로 동일
np.append(a, b, axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [52]:
# 열의 개수가 다른 배열과의 결합
c = np.arange(30, 45).reshape(3, 5)
np_print(c)


    type : <class 'numpy.ndarray'>  
    shape : (3, 5)  
    dimension : 2  
    dtype : int32
    data :
 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
    


In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# 열갯수(가로길이)가 맞지 않으면 axis=0로 추가 불가
np.append(a, c, axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [57]:
# 행 단위로 결합할 수 있는 구조로 변경
c.resize((5, 3))
c

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [58]:
np.append(a, c, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [59]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
# 행의 개수가 다른 배열과의 결합
d = np.arange(90, 102).reshape(4, 3)
np_print(d)


    type : <class 'numpy.ndarray'>  
    shape : (4, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]]
    


In [61]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [62]:
np.append(b, d.reshape(3,4), axis=1)

array([[ 10,  11,  12,  90,  91,  92,  93],
       [ 13,  14,  15,  94,  95,  96,  97],
       [ 16,  17,  18,  98,  99, 100, 101]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가 
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음

In [5]:
# 1이상 10미만 범위에서 1씩 증가하는 숫자로 3 x 3 구조의 배열 생성
arr = np.arange(1, 10).reshape(3, 3)
np_print(arr)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [6]:
# axis를 지정하지 않는 경우 : arr을 1차원 배열로 변형, 지정한 index에 값 추가
# 2d array를 1d array로 변형, 1번 인덱스에 100 추가
np.insert(arr, 1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [7]:
# axis = 0 : 행 갯수 추가(index 행을 기준으로 추가)
# a 배열의 1번 인덱스 행에 100을 추가 => 행의 내부 요소 개수만큼 100이 추가된다.
np.insert(arr, 1, 100, axis=0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# axis = 1 : 열 방향으로 index 추가
# a 배열의 2번 인덱스 열에 200을 추가
np.insert(arr, 2, 200, axis=1)

array([[  1,   2, 200,   3],
       [  4,   5, 200,   6],
       [  7,   8, 200,   9]])

In [11]:
# 요소마다 다른 값으로 행/열 추가
# 요소의 갯수를 동일하게 작성-> 축을 기준으로 요소의 개수를 결정 -> axis로 축 설정
np.insert(arr, 2, [10,20,30], axis=1)

array([[ 1,  2, 10,  3],
       [ 4,  5, 20,  6],
       [ 7,  8, 30,  9]])

3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [24]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 원본 배열은 변경되지 않음
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.arange(1,10).reshape(3,3)

In [34]:
# axis = 0
# a배열의 1번 행을 삭제
np.delete(a, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
np.delete(a,0,axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [38]:
# 1이상 7미만의 범위에서 1씩 증가하는 숫자로 2x3구조의 배열 a 생성
# 7이상 13미만의 범위에서 1씩 증가하는 숫자로 2x3구조의 배열 b 생성
# 13이상 23미만의 범위에서 1씩 증가하는 숫자로 2x5구조의 배열 c 생성
# 23이상 38미만의 범위에서 1씩 증가하는 숫자로 5x3구조의 배열 d 생성

a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
c = np.arange(13,23).reshape(2,5)
d = np.arange(23,38).reshape(5,3)

In [42]:
print(a); print()
print(b); print()
print(c); print()
print(d); print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[13 14 15 16 17]
 [18 19 20 21 22]]

[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]



In [45]:
# axis=0 (기본값) : 행 방향으로 두 배열 결합
# np.append(a, b)
# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print(np.append(a, b))
print(np.concatenate((a,b)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
# axis=1 : 열 방향으로 두개 결합
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [53]:
# 행 방향으로 결합 : 열 개수 동일
np.concatenate((a,c), axis=1)

array([[ 1,  2,  3, 13, 14, 15, 16, 17],
       [ 4,  5,  6, 18, 19, 20, 21, 22]])

In [55]:
# 열 방향으로 결합 : 행 개수 동일
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [56]:
np.concatenate((a,d), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

- vstack() 메서드
    - np.vstack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 행 방향(수직 방향)으로 결합
    - 열의 개수가 동일해야 함
    - np.concatenate((arr1, arr2 ...), axis=0)과 동일한 결과
    - 원본 배열들은 변경되지 않음

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
d

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [68]:
# 열 개수가 동일한 두개의 배열을 행 방향으로 결합(세로길이 증가)
np.vstack((a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [70]:
# 4개 배열 결합
np.vstack((a,b,a,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

In [72]:
# 열 개수가 다른 배열간 결합은 불가능
np.vstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

- np.hstack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 열 방향(수평 방향)으로 결합
    - 행의 개수가 동일해야 함
    - np.concatenate((arr1, arr2 ...), axis=1)과 동일한 결과

In [74]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [78]:
# 4개의 배열 결합
np.hstack((b,c,b,c))

array([[ 7,  8,  9, 13, 14, 15, 16, 17,  7,  8,  9, 13, 14, 15, 16, 17],
       [10, 11, 12, 18, 19, 20, 21, 22, 10, 11, 12, 18, 19, 20, 21, 22]])

- stack() 메서드
    - np.stack((arr1, arr2 ...))
    - 튜플로 전달받은 여러 개의 배열을 3차원으로 결합
    - 행, 열의 구조가 동일해야 함

In [80]:
x = np.stack((a,b,a,b,))
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (4, 2, 3)  
    dimension : 3  
    dtype : int32
    data :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
    


5) 배열 분리
- np.vsplit(arr, indices_or_sections)
    - 배열을 행 방향(수평 방향)으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 분리할 그룹 개수를 지정 : 균등하게 분리
    - 분리할 기준 인덱스를 리스트로 전달 : 균등하지 않게 분리
    - 원본 배열의 구조(shape)과 비교하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [82]:
# 1이상 37미만의 범위에서 1씩 증가하는 숫자로 6 x 6 구조의 배열 a 생성
a = np.arange(1, 37).reshape(6, 6)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (6, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
    


In [93]:
# 결과 배열의 개수를 기준으로 나누기
# 원본 배열을 행 방향으로 3개로 분리
# 반환값 : 분할된 배열을 아이템으로 가지는 리스트
x = np.vsplit(a, 3)
print(type(x))
x

<class 'list'>


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [94]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [98]:
x[0].shape

(2, 6)

In [100]:
# a 배열이 정수로 나누어 떨어지지 않게 나누는 경우 -> 에러 발생
# np.vsplit(a, 4) // error

In [101]:
# 균등하지 않게 나누는 방법
# 나누고자 하는 행 번호를 리스트로 전달
# 0~0번, 1~1번, 2~3번, 4~끝
np.vsplit(a, [1,2,4])

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

- np.hsplit(arr, indices_or_sections)
    - 배열을 열 방향(수직 방향)으로 분리하여 각 배열을 리스트로 묶어서 반환
    - 최종적으로 분리할 그룹 개수를 지정하거나 분리할 기준 인덱스를 지정
    - 원본 배열의 구조(shape)과 비교하여 아이템 개수가 변경
    - 원본 배열은 변경되지 않음

In [102]:
# 사용할 배열 확인
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [109]:
# 원본 배혈을 열 방향으로 6개로 분리
# 반환값 :
x = np.hsplit(a,6)
x

[array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]), array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]), array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [115]:
# 균등하지 않은 기준으로 분리
# 2열, 5열 직전에 금긋기
x= np.hsplit(a, [2,5])
for i in x:
    print(i); 

[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]
 [27 28 29]
 [33 34 35]]
[[ 6]
 [12]
 [18]
 [24]
 [30]
 [36]]


- np.split(arr, indices_or_sections, axis=0)
    - axis = 0(기본값) : 행 단위로 분리
    - axis = 1 : 열 단위로 분리
    - 원본 배열은 변경되지 않음

In [123]:
# 균등하지 않게 행 기준으로 분리(vsplit)
np.split(a, [3, 4], axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [126]:
# 균등한 간격으로 열 기준으로 3개 분리
np.split(a,3, axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]