# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [2]:
import numpy as np

In [3]:
arr2 = np.array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

# 3차원 배열 생성
# 구조 : 2개의 층, 4행, 3열
# np.arange() => 24개의 size
arr3 = np.arange(0, 24).reshape((2, 4, 3))
np_print(arr3)

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [4]:
data = [[1,2,3,4],
        [70, 97, 45, 56],
        [87, 84, 33, 67],
        [46, 80, 75, 78]]
arr = np.array(data)

### 조건 색인(Boolean Indexing)

- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

### 연습문제

조건색인을 활용해 공무원시험의 합격자 평균을 구해주세요.
합격점수는 60점 이상입니다.

아래는 시험 점수 결과입니다.<br>
[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51]

In [5]:
score = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

### 배열 복사

- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌 원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성 : arr.copy() / np.copy(arr)

# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

In [9]:
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 변환

#### 1. 전치(Transpose) 
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음
    
<img src='img/transpose.png' width='200' height='200' align='left'>

### 2. 배열 형태 변경
- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

`#### 3. 요소 변경, 추가, 삭제

1) 요소 변경
- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우 
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [10]:
# 행의 개수가 다른 배열과의 결합
d = np.arange(90, 102).reshape(4,3)
np_print(d)


    type : <class 'numpy.ndarray'>  
    shape : (4, 3)  
    dimension : 2  
    dtype : int32
    data :
 [[ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]]
    
